### ISSUE TITLE
Error deploying EVM contract on create: evm: max code size exceeded

### ISSUE THREAD

**Issue by e11io** [loomnetwork/go-loom#108]
Is there a way to configure `gasLimit` when running a loom node?
`Failed to commit Tx: [DeployTxHandler] Error deploying EVM contract on create: evm: max code size exceeded`

Contract deployment to a PoA network with 8M gasLimit works fine.

**Comment by crackwei** [comment]
the same problem to me.

**Comment by enlight** [comment]
While the gas limit can be adjusted, the max code size is hard coded as 24,576 bytes, same as Ethereum.

**Comment by agunnell** [comment]
Ethereum's gas limit is 6,721,975.

Loom's is 4,915,200. 

I received this error due to the fact that Loom has a gas limit that is 27% less than Ethereum's.
