### ISSUE TITLE
Issue with transaction using go client

### ISSUE THREAD

**Issue by coinsandsteeldev** [loomnetwork/go-loom#109]
Full code to reproduce issue is [here](https://github.com/coinsandsteel/go-tx-issue-mre)
Loom node i ran is 375 build. Failed transaction call as result.

**Comment by enlight** [comment]
Unable to reproduce with build 375, or later, txs are delivered without error.

I would suggest:
- Checking your GOPATH is set correctly, and contains the latest `go-loom`
- Checking that an older instance of the contract isn't still running when executing `loom run`
