### ISSUE TITLE
ErrMethodNotFound should tell you which method wasn't found

### ISSUE THREAD

**Issue by felzix** [loomnetwork/go-loom#144]
I'm getting the ErrMethodNotFound error message when starting up a contract. Since I haven't called anything myself, it's not obvious which method can't be found. (EDIT: My `Init` method had the wrong signature.)

It looks like this: `panic: rpc error: code = Unknown desc = method not found`

The line that looks to be throwing the error is in `go-loom/plugin/contractpb/servicemap.go`, [line 203](https://github.com/loomnetwork/go-loom/blob/9573f2d55431a90aadfd8c5178176df2dc56b212/plugin/contractpb/servicemap.go#L203).

If this is something people want and someone cares to give me a little guidance then I'll make the patch myself.

**Comment by enlight** [comment]
Yes, the error should mention the method name.
