### ISSUE TITLE
make example-cli fail

### ISSUE THREAD

**Issue by kclick91** [loomnetwork/go-loom#195]
After running "make example-cli" I receive this error.

protoc --plugin=./protoc-gen-gogo -I/src -I/usr/local/include --gogo_out=plugins=grpc:/src github.com/loomnetwork/go-loom/types/types.proto
/src: warning: directory does not exist.
github.com/loomnetwork/go-loom/types/types.proto: No such file or directory
Makefile:44: recipe for target 'types/types.pb.go' failed
make: *** [types/types.pb.go] Error 1

**Comment by Jravvit** [comment]
This problem occurs because you have not added gopath.
You should add $GOPATH in .bashrc.

like this 

//.bashrc
export GOPATH="in/your/go/path"

after save, do this command

source .bashrc

**Comment by enlight** [comment]
Seems to have been resolved.
