### ISSUE TITLE
fix capitalization in `Delegation` fields

### ISSUE THREAD

**Issue by aupiff** [loomnetwork/go-loom#267]
in dposv2 types, certain field use camelCase while the rest of the fields are snake_case. Everything should be snake_case.

**Comment by gakonst** [comment]
Don't think so? Declaring the enum type in go-loom is camelcase which is fine, but the actual variable in the proto is snake case.

**Comment by aupiff** [comment]
these should be snake case to be consistent with the rest of the code:
- https://github.com/loomnetwork/go-loom/blob/master/builtin/types/dposv2/dposv2.proto#L45
- https://github.com/loomnetwork/go-loom/blob/master/builtin/types/dposv2/dposv2.proto#L44
- https://github.com/loomnetwork/go-loom/blob/master/builtin/types/dposv2/dposv2.proto#L235
