### ISSUE TITLE
Main Function of this project

### ISSUE THREAD

**Issue by grandbaiyi** [loomnetwork/go-loom#394]
Hi, which file is the main function of go-loom? Not all open source?

Thanks.

**Comment by grandbaiyi** [comment]
Who can reply me?

**Comment by enlight** [comment]
You can ask questions like these in our Telegram group https://t.me/LoomSDK

**Comment by grandbaiyi** [comment]
Sorry, I can't access the Telegram as I am in China. could you please tell me which file the main function of go-loom here?
