### ISSUE TITLE
build example-cli fail

### ISSUE THREAD

**Issue by LyonNee** [loomnetwork/go-loom#408]
lyonnee@lyonnee-Inspiron-7348: ~
/go/src/github.com/loomnetwork/go-loom/examples/cli$ go build cli.go
 github.com/loomnetwork/go-loom/crypto
../../crypto/yubihsm.go:313:18: undefined: secp256k1.NormalizeLaxDERSignature
lyonnee@lyonnee-Inspiron-7348:~/go/src/github.com/loomnetwork/go-loom/examples/c

**Comment by LyonNee** [comment]
lyonnee@lyonnee-Inspiron-7348:~/go/src/github.com/loomnetwork/go-loom$ make example-cli
protoc --plugin=./protoc-gen-gogo -I/home/lyonnee/go/src -I/usr/local/include --gogo_out=plugins=grpc:/home/lyonnee/go/src github.com/loomnetwork/go-loom/plugin/types/types.proto
github.com/loomnetwork/go-loom/plugin/types/types.proto: No such file or directory
Makefile:69: recipe for target 'plugin/types/types.pb.go' failed
make: *** [plugin/types/types.pb.go] Error 1

**Comment by mattkanwisher** [comment]
https://loomx.io/developers/en/prereqs-all.html

**Comment by mattkanwisher** [comment]
missing prereqs in guide above
