### ISSUE TITLE
DelegationMap on dposV3 does not return correct timestamps for lockTime

### ISSUE THREAD

**Issue by olwee** [loomnetwork/go-loom#411]
`{                      
  "amount": {     
    "Value": 11178332149047339519478
  },                               
  "weightedAmount": {                          
    "Value": 32503332149047339519478
  },                    
  "delegations": [           
    {                                          
      "delegator": {
        "chainId": "default", 
        "local": "NkAOCGKjgU0Fp3+iil1Zt8L92M0="
      },                                       
      "validator": {                  
        "chainId": "default",
        "local": "pbLAjB3NWNgZMXt5y8m1qFZr33M="
      },                                       
      "updateValidator": null,
      "index": "9",                
      "amount": {                       
        "Value": 6100000000000000000000
      },                              
      "updateAmount": {
        "Value": 0     
      },          
      "locktimeTier": "TIER_TWO",
      "updateLocktimeTier": "TIER_ZERO",
      "lockTime": "1577217645",                
      "state": "BONDED",       
      "referrer": ""    
    },`'

Above output is from dposv3 call from the CLI, getDelegation.

**Comment by enlight** [comment]
What value were you expecting the `lockTime` to show?

**Comment by olwee** [comment]
So in this case, the `lockTime` is `Tuesday, December 24, 2019 8:00:45 PM`. The locktimeTier, indicates a `TIER_TWO` which is 3 months. This means that the delegation has started in September, which is not possible.

**Comment by pathornteng** [comment]
`TIER_TWO` indicates that the delegation is locked for 6 months, not 3 months. So the delegation you mentioned started in June.

**Comment by olwee** [comment]
Ah I see, thanks
