### ISSUE TITLE
Add in BlockHeight in protobuf for dposV3 for Delegation Type

### ISSUE THREAD

**Issue by olwee** [loomnetwork/go-loom#412]
In order to show delegation statistics for analysis, it is useful to know the block height the delegation was created. This was available previously in dposV2

**Comment by enlight** [comment]
Now that it's possible to combine delegations, it isn't clear what the block height field should contain. The field wasn't used in DPOSv2 and it would be confusing with multiple delegations. It should be possible to calculate all the necessary statistics by checking events.

**Comment by olwee** [comment]
Ok, let us try that
